Add missing `require 'io/console'`
Without this I get the following error when using `--parallel`.
```
NoMethodError: undefined method `cooked!' for #<IO:<STDERR>>>
```

From https://ruby-doc.org/stdlib-2.5.0/libdoc/io/console/rdoc/IO.html#method-i-cooked
> You must require ‘io/console’ to use this method.